exclude: '.md|.csv|node_modules|.git|.tox|.venv'
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings.
      - id: requirements-txt-fixer
        name: Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
      - id: check-yaml
        name: Check YAML files for syntax errors
      - id: check-json
        name: Check JSON files for syntax errors
      - id: check-merge-conflict
        name: Check for merge conflict strings
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -  id: detect-secrets
       name: Check for secrets within the codebase
       args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
