name: Feature Request
description: Request a new feature
title: "feature: "
labels: ["enhancement", "flask"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the requested feature.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case or scenario where this feature would be beneficial.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request (optional).
    validations:
      required: false