name: Question
description: Ask a question
title: "question: "
labels: ["question", "flask"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please check the [project wiki](https://github.com/datasciencecampus/flask-template/wiki) and [FAQs](https://github.com/datasciencecampus/flask-template/wiki/FAQ's) first.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Provide a clear and concise description of your question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context, such as the steps you've taken or error messages you're encountering (if applicable).
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details (optional)
      description: Provide details about your development environment (e.g., operating system, Flask version, Python version).
    validations:
      required: false